apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../
namePrefix: user-service- # Prefix or just override name? Let's use name override via patch
patches:
- target:
    kind: Deployment
    name: app
  patch: |-
    - op: replace
      path: /metadata/name
      value: user-service
    - op: replace
      path: /spec/template/metadata/labels/app
      value: user-service
    - op: replace
      path: /spec/selector/matchLabels/app
      value: user-service
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: us-central1-docker.pkg.dev/journeyiq-prod/journeyiq-services/user-service:latest
- target:
    kind: Service
    name: app
  patch: |-
    - op: replace
      path: /metadata/name
      value: user-service
    - op: replace
      path: /spec/selector/app
      value: user-service
