apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../
namePrefix: search-service- 
patches:
- target:
    kind: Deployment
    name: app
  patch: |-
    - op: replace
      path: /metadata/name
      value: search-service
    - op: replace
      path: /spec/template/metadata/labels/app
      value: search-service
    - op: replace
      path: /spec/selector/matchLabels/app
      value: search-service
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: us-central1-docker.pkg.dev/journeyiq-prod/journeyiq-services/search-service:latest
- target:
    kind: Service
    name: app
  patch: |-
    - op: replace
      path: /metadata/name
      value: search-service
    - op: replace
      path: /spec/selector/app
      value: search-service
